package com.parkingapp;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

// Component Interface
interface ParkingComponent {
    String getId();
    void enable();
    void disable();
    boolean isEnabled();
}

// Composite Class (ParkingLot)
class ParkingLot implements ParkingComponent {
    private String id;
    private List<ParkingComponent> parkingSpaces;
    private boolean enabled;

    public ParkingLot(String id) {
        this.id = id;
        this.parkingSpaces = new ArrayList<>();	//LIST OF 100 autogenerated spots
        this.enabled = true; // Initially enabled
        initializeParkingSpaces(); // Ensure 100 parking spaces
    }

    // Initialize Parking Lot with 100 Parking Spaces
    private void initializeParkingSpaces() {
        for (int i = 1; i <= 100; i++) {
            // Format 'i' as a 3-digit number (e.g. "001", "010", "100")
            String paddedNum = String.format("%03d", i);
            // Now create the ID as "Parking 001", "Parking 002", etc.
            parkingSpaces.add(new ParkingSpace(this.id + paddedNum, this.id));
        }
    }

    public List<ParkingComponent> getParkingSpaces() {
        return parkingSpaces;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void enable() {
        this.enabled = true;
        for (ParkingComponent space : parkingSpaces) {
            space.enable();
        }
    }

    @Override
    public void disable() {
        this.enabled = false;
        for (ParkingComponent space : parkingSpaces) {
            space.disable();
        }
    }
    
    @Override
    public boolean isEnabled() {
    	return enabled;
    }
}


// Leaf Class (ParkingSpace)
class ParkingSpace implements ParkingComponent {
    private String id;
    private String parentId;
    private boolean enabled;
    private boolean occupied;
    private Sensor sensor;

    public ParkingSpace(String id, String parentId) {
    	this.parentId = parentId;	//location of parking space(which lot it belongs to)
        this.id = id;
        this.enabled = true; // Initially enabled
        this.occupied = false;
        this.sensor = new Sensor(this);
    }

    @Override
    public String getId() {
        return id;
    }
    
    //return location
    public String getParentId() {
        return parentId;
    }

    @Override
    public void enable() {
        this.enabled = true;
    }

    @Override
    public void disable() {
        this.enabled = false;
    }
    
    @Override
    public boolean isEnabled() {
    	return enabled;
    }

    public boolean isOccupied() {
        return occupied;
    }

    // Simulating a car entering the parking space
    public void carEnters(String carPlate) {
        if (!enabled ) {
            System.out.println("Parking Space " + id + " is not available.");
            return;
        }
        if (!occupied) {
            occupied = true;
            sensor.detectCar(carPlate);
        } else {
            System.out.println("Parking Space " + id + " is already occupied.");
        }
    }

    // Simulating a car leaving the parking space
    public void carLeaves() {
        if (occupied) {
            occupied = false;
            System.out.println("Parking Space " + id + " is now available.");
        } else {
            System.out.println("Parking Space " + id + " was already vacant.");
        }
    }
}

// Sensor Class (Handles Car Detection and Booking Verification for deposit)
class Sensor {
    private ParkingSpace parkingSpace;
    private static final Random random = new Random();

    public Sensor(ParkingSpace parkingSpace) {
        this.parkingSpace = parkingSpace;
    }

    // Simulating Car Detection
    public void detectCar(String carPlate) {
        System.out.println("Sensor detected car: " + carPlate + " in " + parkingSpace.getId());

        // Simulating verification of booking
        boolean hasValidBooking = random.nextBoolean(); // Randomly simulating booking status
        if (hasValidBooking) {
            //processDepositReturn(carPlate);
        } else {
            System.out.println("Warning: Car " + carPlate + " does not have a valid booking.");
        }
    }
}
